"""Reset dan buat ulang semua tabel

Revision ID: 362539dd9107
Revises: 
Create Date: 2025-07-20 14:35:58.794529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362539dd9107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=False),
    sa.Column('isi_berita', sa.Text(), nullable=False),
    sa.Column('url_gambar_utama', sa.String(length=255), nullable=True),
    sa.Column('tanggal_publikasi', sa.DateTime(), nullable=True),
    sa.Column('penulis', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pengaduan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pembuat_id', sa.Integer(), nullable=True),
    sa.Column('nama_pelapor', sa.String(length=100), nullable=True),
    sa.Column('kontak_pelapor', sa.String(length=100), nullable=True),
    sa.Column('judul', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('url_bukti_media', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tanggal_pengaduan', sa.DateTime(), nullable=True),
    sa.Column('tanggal_update_status', sa.DateTime(), nullable=True),
    sa.Column('respon_admin', sa.Text(), nullable=True),
    sa.Column('notifikasi_terkirim', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pembuat_id'], ['user.id'], name='fk_pengaduan_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengaduan')
    op.drop_table('user')
    op.drop_table('berita')
    # ### end Alembic commands ###
