"""Add APBDes model

Revision ID: d6f6019fb90c
Revises: 
Create Date: 2025-06-28 09:39:42.114783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f6019fb90c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apb_des',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('url_file_apbdes', sa.String(length=255), nullable=True),
    sa.Column('tanggal_unggah', sa.DateTime(), nullable=True),
    sa.Column('pengunggah_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pengunggah_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apb_des')
    # ### end Alembic commands ###
